import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex justify-center bg-slate-400">
        <div className="w-full max-w-[600px] min-h-screen bg-white relative">
          {children}
        </div>
      </body>
    </html>
  );
}
